- hosts: localhost
  tasks: 
    - name: "Esperar hasta que fichero exista"
      wait_for: path=/tmp/existo
    - name: "Esperar hasta que fichero no exista"
      wait_for: path=/tmp/existo state=absent
      
